version: 1.0.{build}
image: Visual Studio 2017
install:
- cmd: >-
    choco install -y python2

    pip install pywin32
build_script:
- cmd: >-
    python build_ffmpeg.py  -nw 0.33.3 -pc -ta x64

artifacts:
- path: releases/*.zip
